In [117]:
import pandas as pd
import numpy as np  
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)
from datetime import datetime

In [ ]:
today_date = datetime.today().strftime('%Y.%m.%d')
print(today_date)

2025.10.04

In [115]:
df = pd.read_excel('WEOApr2025all.xlsx')
df=df[df['ISO'].notna()]
df.rename(columns={'ISO':'ISO3'},inplace=True)
df.head()

,WEO Country Code,ISO3,WEO Subject Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030,Estimates Start After
0,512,AFG,NGDP_R,Afghanistan,"Gross domestic product, constant prices",Expressed in billions of national currency uni...,National currency,Billions,Source: National Statistics Office Latest actu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,453.484,492.903,496.209,554.91,584.658,662.65,688.247,829.924,899.956,958.266,1092.118,1154.178,1185.306,1197.012,1222.917,1255.288,1270.216,1319.902,1288.869,1101.445,1032.712,1056.123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0
1,512,AFG,NGDP_RPCH,Afghanistan,"Gross domestic product, constant prices",Annual percentages of constant price GDP are y...,Percent change,Units,"See notes for: Gross domestic product, consta...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.692,0.671,11.83,5.361,13.34,3.863,20.585,8.438,6.479,13.968,5.683,2.697,0.988,2.164,2.647,1.189,3.912,-2.351,-14.542,-6.24,2.267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0
2,512,AFG,NGDP,Afghanistan,"Gross domestic product, current prices",Expressed in billions of national currency uni...,National currency,Billions,Source: National Statistics Office Latest actu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,178.756,220.013,246.21,304.926,345.817,427.495,517.509,607.227,711.759,836.222,1033.591,1116.827,1183.039,1226.57,1222.917,1285.46,1327.69,1469.596,1547.289,1251.172,1283.442,1350.91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0
3,512,AFG,NGDPD,Afghanistan,"Gross domestic product, current prices",Values are based upon GDP in national currency...,U.S. dollars,Billions,"See notes for: Gross domestic product, curren...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.367,4.553,5.146,6.167,6.925,8.556,10.297,12.066,15.325,17.89,20.293,20.17,20.616,20.057,18.02,18.883,18.336,18.876,20.136,14.278,14.501,17.248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0
4,512,AFG,PPPGDP,Afghanistan,"Gross domestic product, current prices",These data form the basis for the country weig...,Purchasing power parity; international dollars,Billions,"See notes for: Gross domestic product, curren...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.742,25.206,26.058,30.054,32.642,37.999,40.227,48.807,53.568,58.216,67.583,72.639,75.898,77.358,79.784,83.362,89.369,97.801,100.898,85.768,86.149,91.272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0

## Dictionary

In [89]:
dict_weo=df[[ 'WEO Subject Code','Subject Descriptor','Subject Notes','Units','Scale',]]
dict_weo.drop_duplicates(inplace=True)
#dict_weo.to_excel('weo_dictionary.xlsx',index=False)

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_45496\1582358271.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dict_weo.drop_duplicates(inplace=True)

## Cleaning

In [90]:
df.drop(columns=['Subject Descriptor','Subject Notes','Units','Scale','Country/Series-specific Notes','Estimates Start After'],inplace=True)

In [91]:
df['WEO Subject Code'].unique()

array(['NGDP_R', 'NGDP_RPCH', 'NGDP', 'NGDPD', 'PPPGDP', 'NGDP_D',
       'NGDPRPC', 'NGDPRPPPPC', 'NGDPPC', 'NGDPDPC', 'PPPPC',
       'NGAP_NPGDP', 'PPPSH', 'PPPEX', 'NID_NGDP', 'NGSD_NGDP', 'PCPI',
       'PCPIPCH', 'PCPIE', 'PCPIEPCH', 'TM_RPCH', 'TMG_RPCH', 'TX_RPCH',
       'TXG_RPCH', 'LUR', 'LE', 'LP', 'GGR', 'GGR_NGDP', 'GGX',
       'GGX_NGDP', 'GGXCNL', 'GGXCNL_NGDP', 'GGSB', 'GGSB_NPGDP',
       'GGXONLB', 'GGXONLB_NGDP', 'GGXWDN', 'GGXWDN_NGDP', 'GGXWDG',
       'GGXWDG_NGDP', 'NGDP_FY', 'BCA', 'BCA_NGDPD'], dtype=object)

In [103]:
panel_df = pd.melt(df, id_vars=['WEO Country Code','ISO3', 'Country', 'WEO Subject Code'], 
                   var_name='Year', value_name='Value')

panel_df['Year'] = panel_df['Year'].astype(int)
panel_df['Value'] = pd.to_numeric(panel_df['Value'], errors='coerce')
pivot_df = panel_df.pivot(index=['WEO Country Code', 'ISO3', 'Country', 'Year'], 
                          columns='WEO Subject Code', 
                          values='Value').reset_index()

pivot_df = pivot_df[['WEO Country Code', 'ISO3', 'Country', 'Year',
                     'NGDP_R', 'NGDP_RPCH', 'NGDP', 'NGDPD', 'PPPGDP', 'NGDP_D',
                    'NGDPRPC', 'NGDPRPPPPC', 'NGDPPC', 'NGDPDPC', 'PPPPC',
                    'NGAP_NPGDP', 'PPPSH', 'PPPEX', 'NID_NGDP', 'NGSD_NGDP', 'PCPI',
                    'PCPIPCH', 'PCPIE', 'PCPIEPCH', 'TM_RPCH', 'TMG_RPCH', 'TX_RPCH',
                    'TXG_RPCH', 'LUR', 'LE', 'LP', 'GGR', 'GGR_NGDP', 'GGX',
                    'GGX_NGDP', 'GGXCNL', 'GGXCNL_NGDP', 'GGSB', 'GGSB_NPGDP',
                    'GGXONLB', 'GGXONLB_NGDP', 'GGXWDN', 'GGXWDN_NGDP', 'GGXWDG',
                    'GGXWDG_NGDP', 'NGDP_FY', 'BCA', 'BCA_NGDPD']] 
pivot_df.sort_values(by=['ISO3', 'Year'], inplace=True)
pivot_df.reset_index(drop=True, inplace=True)
pivot_df.columns.name = None
pivot_df

,WEO Country Code,ISO3,Country,Year,NGDP_R,NGDP_RPCH,NGDP,NGDPD,PPPGDP,NGDP_D,NGDPRPC,NGDPRPPPPC,NGDPPC,NGDPDPC,PPPPC,NGAP_NPGDP,PPPSH,PPPEX,NID_NGDP,NGSD_NGDP,PCPI,PCPIPCH,PCPIE,PCPIEPCH,TM_RPCH,TMG_RPCH,TX_RPCH,TXG_RPCH,LUR,LE,LP,GGR,GGR_NGDP,GGX,GGX_NGDP,GGXCNL,GGXCNL_NGDP,GGSB,GGSB_NPGDP,GGXONLB,GGXONLB_NGDP,GGXWDN,GGXWDN_NGDP,GGXWDG,GGXWDG_NGDP,NGDP_FY,BCA,BCA_NGDPD
0,314,ABW,Aruba,1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,314,ABW,Aruba,1981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,314,ABW,Aruba,1982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,314,ABW,Aruba,1983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,314,ABW,Aruba,1984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9991,698,ZWE,Zimbabwe,2026,0.107,4.640,1319.643,39.491,100.373,1228192.011,6.061,4748.232,74436.167,2227.553,5661.688,NaN,0.046,13.147,NaN,NaN,1204688.561,9.627,1247473.519,7.969,NaN,5.741,NaN,3.158,NaN,NaN,17.729,246.746,18.698,240.923,18.257,5.823,0.441,NaN,NaN,20.180,1.529,NaN,NaN,739.670,56.051,1319.643,1.210,3.063
9992,698,ZWE,Zimbabwe,2027,0.111,3.630,1476.529,40.925,105.931,1326067.371,6.150,4818.449,81556.530,2260.495,5851.140,NaN,0.046,13.939,NaN,NaN,1300690.916,7.969,1346885.434,7.969,NaN,3.672,NaN,3.996,NaN,NaN,18.104,282.266,19.117,269.182,18.231,13.085,0.886,NaN,NaN,28.764,1.948,NaN,NaN,786.902,53.294,1476.529,1.198,2.927
9993,698,ZWE,Zimbabwe,2028,0.115,3.458,1649.212,42.340,111.880,1431640.782,6.231,4881.536,89202.367,2290.091,6051.366,NaN,0.046,14.741,NaN,NaN,1404343.758,7.969,1454219.544,7.969,NaN,16.126,NaN,4.827,NaN,NaN,18.488,316.597,19.197,300.172,18.201,16.425,0.996,NaN,NaN,33.448,2.028,NaN,NaN,862.793,52.315,1649.212,1.226,2.895
9994,698,ZWE,Zimbabwe,2029,0.119,3.532,1843.656,43.836,117.952,1545838.896,6.317,4948.697,97642.962,2321.598,6246.941,NaN,0.047,15.631,NaN,NaN,1516256.756,7.969,1570107.174,7.969,NaN,12.334,NaN,7.798,NaN,NaN,18.882,355.400,19.277,334.492,18.143,20.907,1.134,NaN,NaN,38.866,2.108,NaN,NaN,930.773,50.485,1843.656,1.120,2.554
9995,698,ZWE,Zimbabwe,2030,0.123,3.532,2056.061,45.384,124.404,1665122.487,6.403,5016.410,106616.652,2353.365,6450.939,NaN,0.047,16.527,NaN,NaN,1637088.169,7.969,1695229.959,7.969,NaN,3.651,NaN,3.729,NaN,NaN,19.285,396.345,19.277,372.362,18.110,23.983,1.166,NaN,NaN,43.344,2.108,NaN,NaN,993.329,48.312,2056.061,0.996,2.196

In [109]:
pivot_df['GDP_N_GR'] = ((pivot_df['NGDP'] / pivot_df['NGDP'].shift(1) - 1)).where(pivot_df['NGDP'].shift(1).notna())
pivot_df['GDP_R_GR'] = ((pivot_df['NGDP_R'] / pivot_df['NGDP_R'].shift(1) - 1)).where(pivot_df['NGDP_R'].shift(1).notna())

pivot_df['GDP_CRISIS'] = pivot_df['GDP_R_GR'] < 0
pd.set_option('future.no_silent_downcasting', True)
pivot_df['GDP_CRISIS'] = pivot_df['GDP_CRISIS'].replace({True: 1, False: 0})
pivot_df['GDP_R_PC'] = (pivot_df['NGDP_R'] * 1e9) / (pivot_df['LP'] * 1e6)
pivot_df['GDP_R_PC_GR'] = ((pivot_df['GDP_R_PC'] / pivot_df['GDP_R_PC'].shift(1) - 1)).where(pivot_df['GDP_R_PC'].shift(1).notna())
pivot_df['GDP_PPP_PC'] = pivot_df['PPPGDP'] / (pivot_df['LP'] * 1e6)
pivot_df['INFLATION'] = ((pivot_df['PCPI'] / pivot_df['PCPI'].shift(1) - 1)).where(pivot_df['PCPI'].shift(1).notna())
pivot_df['INFLATION_END'] = ((pivot_df['PCPIE'] / pivot_df['PCPIE'].shift(1) - 1)).where(pivot_df['PCPIE'].shift(1).notna())

pivot_df.head()

,WEO Country Code,ISO3,Country,Year,NGDP_R,NGDP_RPCH,NGDP,NGDPD,PPPGDP,NGDP_D,NGDPRPC,NGDPRPPPPC,NGDPPC,NGDPDPC,PPPPC,NGAP_NPGDP,PPPSH,PPPEX,NID_NGDP,NGSD_NGDP,PCPI,PCPIPCH,PCPIE,PCPIEPCH,TM_RPCH,TMG_RPCH,TX_RPCH,TXG_RPCH,LUR,LE,LP,GGR,GGR_NGDP,GGX,GGX_NGDP,GGXCNL,GGXCNL_NGDP,GGSB,GGSB_NPGDP,GGXONLB,GGXONLB_NGDP,GGXWDN,GGXWDN_NGDP,GGXWDG,GGXWDG_NGDP,NGDP_FY,BCA,BCA_NGDPD,GDP_N_GR,GDP_R_GR,GDP_CRISIS,GDP_R_PC,GDP_R_PC_GR,GDP_PPP_PC,INFLATION,INFLATION_END
0,314,ABW,Aruba,1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
1,314,ABW,Aruba,1981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
2,314,ABW,Aruba,1982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
3,314,ABW,Aruba,1983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
4,314,ABW,Aruba,1984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN

In [119]:
pivot_df.to_excel(f'({today_date})weo_cleaned.xlsx',index=False)